#!/bin/sh

cd "$(dirname "$0")"

[ -f '.env' ] && eval "$(cat '.env' | sed -E 's/^(.+)/export \1/')"

TASK_BIN="task"

if command -v go-task >/dev/null 2>&1; then
  TASK_BIN="go-task"
fi

exec ${TASK_BIN} \
  --taskfile taskfile.yml \
  --sort none \
  ${@:-'--list-all'}
